name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
      - name: Merge generated reports into one
        run: yarn run merge:reports
      - name: Create md report
        run: yarn run create:markdown:report
      - name: List dir
        run: ls .
